apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.12
        env:
          - name: SECRET_USERNAME
            valueFrom:
              secretKeyRef:
                name: account
                key: username
          - name: SECRET_PASSWORD
            valueFrom:
              secretKeyRef:
                name: account
                key: password
        ports:
        - containerPort: 80
